# Site settings
title: Paulo Romeira
email: paulo@pauloromeira.com
# description: > # this means to ignore newlines until "baseurl:"
    # Página pessoal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pauloromeira.com" # the base hostname & protocol for your site
github_username: pauloromeira

# Build settings
markdown: kramdown
